# Generated by Django 3.0.5 on 2020-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200503_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraefetuada',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
