# Generated by Django 3.0.5 on 2020-05-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200503_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraefetuada',
            name='cliente',
        ),
    ]
