# Generated by Django 3.0.5 on 2020-05-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20200503_1628'),
        ('produtos', '0003_remove_compraefetuada_cliente'),
    ]

    operations = [
    ]
